#include <pic16f1938.h>
#include "LEDDrive.h"

#define DATA_HI_1(){LATBbits.LATB0=1;}
#define DATA_LOW_1(){LATBbits.LATB0=0;}

#define DATA_HI_2(){LATBbits.LATB3=1;}
#define DATA_LOW_2(){LATBbits.LATB3=0;}

#define DATA_HI_3(){LATBbits.LATB4=1;}
#define DATA_LOW_3(){LATBbits.LATB4=0;}

#define DATA_HI_4(){LATBbits.LATB5=1;}
#define DATA_LOW_4(){LATBbits.LATB5=0;}

void SendData(int tape_num){
  int count = 0;
  switch(tape_num){
  case 1:
    while(count<TAPE1_LEDs){
      SendDat1(G1[count]);//RedData
      SendDat1(R1[count]);//GreenData
      SendDat1(B1[count]);//Bluedata
      count++;
    }
    break;
  case 2:
    while(count<TAPE2_LEDs){
      SendDat2(G2[count]);//RedData
      SendDat2(R2[count]);//GreenData
      SendDat2(B2[count]);//Bluedata
      count++;
    }
    break;
  case 3:
    while(count<TAPE3_LEDs){
      SendDat3(G3[count]);//RedData
      SendDat3(R3[count]);//GreenData
      SendDat3(B3[count]);//Bluedata
      count++;
    }
    break;
  case 4:
    while(count<TAPE4_LEDs){
      SendDat4(G4[count]);//RedData
      SendDat4(R4[count]);//GreenData
      SendDat4(B4[count]);//Bluedata
      count++;
    }
    break;
  }
}

void SendDat1(char dat){
    if(dat>>7&0x01){
      DATA_HI_1();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_1();
    }else{
      DATA_HI_1();
      asm("nop");
      DATA_LOW_1();
    }
    if(dat>>6&0x01){
      DATA_HI_1();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_1();
    }else{
      DATA_HI_1();
      asm("nop");
      DATA_LOW_1();
    }
    if(dat>>5&0x01){
      DATA_HI_1();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_1();
    }else{
      DATA_HI_1();
      asm("nop");
      DATA_LOW_1();
    }
    if(dat>>4&0x01){
      DATA_HI_1();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_1();
    }else{
      DATA_HI_1();
      asm("nop");
      DATA_LOW_1();
    }
    if(dat>>3&0x01){
      DATA_HI_1();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_1();
    }else{
      DATA_HI_1();
      asm("nop");
      DATA_LOW_1();
    }
    if(dat>>2&0x01){
      DATA_HI_1();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_1();
    }else{
      DATA_HI_1();
      asm("nop");
      DATA_LOW_1();
    }
    if(dat>>1&0x01){
      DATA_HI_1();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_1();
    }else{
      DATA_HI_1();
      asm("nop");
      DATA_LOW_1();
    }
    if(dat>>0&0x01){
      DATA_HI_1();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_1();
    }else{
      DATA_HI_1();
      asm("nop");
      DATA_LOW_1();
    }
}

void SendDat2(char dat){
    if(dat>>7&0x01){
      DATA_HI_2();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_2();
    }else{
      DATA_HI_2();
      asm("nop");
      DATA_LOW_2();
    }
    if(dat>>6&0x01){
      DATA_HI_2();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_2();
    }else{
      DATA_HI_2();
      asm("nop");
      DATA_LOW_2();
    }
    if(dat>>5&0x01){
      DATA_HI_2();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_2();
    }else{
      DATA_HI_2();
      asm("nop");
      DATA_LOW_2();
    }
    if(dat>>4&0x01){
      DATA_HI_2();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_2();
    }else{
      DATA_HI_2();
      asm("nop");
      DATA_LOW_2();
    }
    if(dat>>3&0x01){
      DATA_HI_2();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_2();
    }else{
      DATA_HI_2();
      asm("nop");
      DATA_LOW_2();
    }
    if(dat>>2&0x01){
      DATA_HI_2();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_2();
    }else{
      DATA_HI_2();
      asm("nop");
      DATA_LOW_2();
    }
    if(dat>>1&0x01){
      DATA_HI_2();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_2();
    }else{
      DATA_HI_2();
      asm("nop");
      DATA_LOW_2();
    }
    if(dat>>0&0x01){
      DATA_HI_2();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_2();
    }else{
      DATA_HI_2();
      asm("nop");
      DATA_LOW_2();
    }
}

void SendDat3(char dat){
    if(dat>>7&0x01){
      DATA_HI_3();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_3();
    }else{
      DATA_HI_3();
      asm("nop");
      DATA_LOW_3();
    }
    if(dat>>6&0x01){
      DATA_HI_3();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_3();
    }else{
      DATA_HI_3();
      asm("nop");
      DATA_LOW_3();
    }
    if(dat>>5&0x01){
      DATA_HI_3();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_3();
    }else{
      DATA_HI_3();
      asm("nop");
      DATA_LOW_3();
    }
    if(dat>>4&0x01){
      DATA_HI_3();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_3();
    }else{
      DATA_HI_3();
      asm("nop");
      DATA_LOW_3();
    }
    if(dat>>3&0x01){
      DATA_HI_3();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_3();
    }else{
      DATA_HI_3();
      asm("nop");
      DATA_LOW_3();
    }
    if(dat>>2&0x01){
      DATA_HI_3();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_3();
    }else{
      DATA_HI_3();
      asm("nop");
      DATA_LOW_3();
    }
    if(dat>>1&0x01){
      DATA_HI_3();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_3();
    }else{
      DATA_HI_3();
      asm("nop");
      DATA_LOW_3();
    }
    if(dat>>0&0x01){
      DATA_HI_3();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_3();
    }else{
      DATA_HI_3();
      asm("nop");
      DATA_LOW_3();
    }
}

void SendDat4(char dat){
    if(dat>>7&0x01){
      DATA_HI_4();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_4();
    }else{
      DATA_HI_4();
      asm("nop");
      DATA_LOW_4();
    }
    if(dat>>6&0x01){
      DATA_HI_4();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_4();
    }else{
      DATA_HI_4();
      asm("nop");
      DATA_LOW_4();
    }
    if(dat>>5&0x01){
      DATA_HI_4();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_4();
    }else{
      DATA_HI_4();
      asm("nop");
      DATA_LOW_4();
    }
    if(dat>>4&0x01){
      DATA_HI_4();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_4();
    }else{
      DATA_HI_4();
      asm("nop");
      DATA_LOW_4();
    }
    if(dat>>3&0x01){
      DATA_HI_4();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_4();
    }else{
      DATA_HI_4();
      asm("nop");
      DATA_LOW_4();
    }
    if(dat>>2&0x01){
      DATA_HI_4();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_4();
    }else{
      DATA_HI_4();
      asm("nop");
      DATA_LOW_4();
    }
    if(dat>>1&0x01){
      DATA_HI_4();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_4();
    }else{
      DATA_HI_4();
      asm("nop");
      DATA_LOW_4();
    }
    if(dat>>0&0x01){
      DATA_HI_4();
      asm("nop");asm("nop");asm("nop");
      DATA_LOW_4();
    }else{
      DATA_HI_4();
      asm("nop");
      DATA_LOW_4();
    }
}
